* A Neighbor Discovery (ND) reflector for OpenBSD

An ND reflector works like ND proxies but does not check the host presence. It listens for a Neighbor Solicitation (NS) packet destined to its subnet and immediately replies to it by sending a neighbor advertisement (NA) packet. Thus it is a reflector.

The ND reflector aims to provide global IPv6 addresses to hosts in an IPv4/v6 dual-stack home network without NAT66 translation as in the following diagram.

#+begin_src picture
               +-------------+                       +------------+            +--------+
               |             | IPv4 PPPoE        Wan | HomeRouter | Lan        |        |
  Internet ----+ ISP Router  +-----------------------+ (OpenBSD)  +------------+  Host  |
               |             | IPv6 over Ethenet     |            |            |        |
               +-------------+  (RA with /64)        +------------+            +--------+
#+end_src

Proper proxies check the presence of the host corresponding to the NS target address by sending an NS packet from the LAN interface. If they receive a reply NA packet, then they proxy it to the original sender.

On the other hand, when a reflector receives an NS packet arriving WAN interface, it consults the routing table checking the destination interface of the NS target address. If the destination interface matches the LAN interface, then the reflector sends an NA packet to the sender of the NS packet.


** Build and install

#+begin_src sh
  mkdir build
  cd build
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make
  doas make install
#+end_src

** Start daemon

#+begin_src sh
  doas rcctl enable ndprd
  doas rcctl set ndprd flags em1 em2
  rcctl get ndprd
  doas rcctl start ndprd
#+end_src

In the above example, =em1= is the WAN interface and =em2= is the LAN interface.

*** debug mode

By specifying the option =-dv=, =ndprd= will run in the foreground (that is, not daemonize) and log to =stderr=.

#+begin_src sh
  doas ndprd -dv em1 em2
#+end_src

If the option =-m= specified, =ndprd= receives NS packets but not send NA packets.

** Testing environment

- OpenBSD 6.9 amd64

** Similar projects

- FreeBSD kernel module for ND proxy
  - https://github.com/AlexandreFenyo/ndproxy
- Linux and FreeBSD deamons for ND proxy
  - https://github.com/DanielAdolfsson/ndppd
